 -- [III] JOIN : 테이블 2개 이상을 연결하여 검색 
 
ALTER SESSION SET NLS_DATE_FORMAT = 'RR/MM/DD';
SELECT * 
    FROM EMP
    WHERE ENAME = 'SCOTT';   -- 부서 번호(DEPTNO 20)

-- CROSS JOIN (FROM절에 테이블 2개이상)

SELECT *
    FROM EMP, DEPT
    WHERE ENAME = 'SCOTT' AND EMP.DEPTNO = DEPT.DEPTNO; -- 4행 = EMP테이블 1행 * DEPT 의 4행
--SELECT *
--    FROM EMP, DEPT;

-- EQUI JOIN (공통 필드의 DEPTNO값이 일치되는 조건만 JOIN) RDBMS


SELECT EMPNO, ENAME, EMP.DEPTNO, DNAME, LOC 
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO;
    
SELECT EMPNO NO, ENAME, E.DEPTNO, DNAME, LOC 
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    ORDER BY NO;
    
    
-- 급여가 2000이상인 직원만 ENAME, JOB, SAL, DNAME, LOC 출력

SELECT ENAME, JOB, SAL, DNAME, LOC
    FROM EMP E, DEPT D
    WHERE SAL>=2000 AND E.DEPTNO = D.DEPTNO
    ORDER BY SAL;
    
    
    
-- LOC 이 CHICAGO 인 사람의 ENAME, JOB, SAL 를 출력

SELECT ENAME, JOB, SAL
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND LOC = 'CHICAGO'
    ORDER BY ENAME;
    
    
-- LOC 이 CHICAGO 인 사람의 ENAME, JOB, SAL, DNAME, LOC 출력

SELECT ENAME, JOB, SAL, DNAME, LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND LOC = 'CHICAGO'
    ORDER BY ENAME;